### ISSUE TITLE
PHAsset GIF support

### ISSUE THREAD

**Issue by chadpod** [kean/DFImageManager#41]
More of a question than a bug, but are GIFs supported for PHAssets or just remote resources loaded via url? I ended up inspecting the UTI in the info dictionary and then loading the GIF as data with the standard -[PHImageManager requestImageDataForAsset:options:resultHandler:].  Thanks and nice framework ... can't believe I hadn't seen it till now.

**Comment by kean** [comment]
> are GIFs supported for PHAssets or just remote resources loaded via url?

GIFs (as well as webp) are supported just for remote resources. `_DFPhotosKitImageFetchOperation` uses `-requestImageForAsset:targetSize:contentMode:options:resultHandler:` under the hood. Changing it to use `-[PHImageManager requestImageDataForAsset:options:resultHandler:]` and built-in image decoder should be just couple of lines of code. Thanks for feedback, I'll take a look into it.

**Comment by kean** [comment]
DFImageFetching should probably return NSData instead of UIImage (DFImageDataFetching). It was returning UIImage because of the AssetsLibrary that doesn't provide access to NSData of thumbnail and fullScreenImage. It might be worth to either simply drop AssetsLibrary support or reimplementing it to work with fullsize image data.

**Comment by kean** [comment]
- Image fetchers (classes conforming to DFImageFetching protocol) are now required to fetch image data (NSData) instead of UIImage, they do not decode data
- Image decoding is now handled by DFImageManager itself

DFPhotosKitImageFetcher:
- DFPhotosKitImageFetcher has a completely new goal now. It no longer tries to mimic PHImageManager as close as possible. Instead it now extends PHImageManager functionality by providing custom image decoding which includes GIF support. As a downside, it is slower when it comes to image previews, however that’s no longer a goal; if the user wants performance as fast as Photos app he should use PHImageManager directly anyway
- Remove DFPhotosKitDeliveryModeKey and DFPhotosKitResizeModeKey which are no longer used

DFURLImageFetcher:
- Rename DFURLResponseDeserializing to DFURLResponseValidating; change classes conforming to this protocol accordingly
- Remove DFURLImageDeserializer

DFAFImageFetcher:
- Remove DFAFImageDeserializer, use AFHTTPResponseSerializer instead

**Comment by kean** [comment]
Overall, these changes lead to much cleaner implementation. And it enables much cleaner progressive JPEG implementation.

**Comment by kean** [comment]
Done in develop branch
